security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\Provider: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Provider
                property: email
    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false
            
        login:
            provider: app_user_provider
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                username_path: email
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
